Repository laisbastosbg/myrror, pull requests merged in 2022-09, with the labels that each got.

#1 Feature/navigation button
  Myrror.xcodeproj/project.pbxproj
  Myrror/Assets.xcassets/AccentColor.colorset/Contents.json
  Myrror/Assets.xcassets/Colors/Contents.json
  Myrror/Assets.xcassets/Colors/Primary.colorset/Contents.json
  Myrror/Assets.xcassets/Colors/TextColor.colorset/Contents.json
  Myrror/SceneDelegate.swift
  Myrror/View/NewReflectionViewController.swift
  Myrror/View/ViewController.swift
Labels: feature

#3 :construction: feat: estrutura da pagina inicial vazia
  Myrror/Assets.xcassets/Images/Contents.json
  Myrror/Assets.xcassets/Images/empty_home.imageset/Contents.json
  Myrror/Assets.xcassets/Images/empty_home.imageset/empty_home.png
  Myrror/Assets.xcassets/Images/empty_home.imageset/empty_home_dark.png
  Myrror/View/ViewController.swift
Labels: feature

#4 Feature/choose topic screen
  Myrror.xcodeproj/project.pbxproj
  Myrror/View/ChooseTopicViewController.swift
  Myrror/View/NewReflectionViewController.swift
  Myrror/View/ViewController.swift
Labels: feature

#7 Feature/solving bugs
  Myrror.xcodeproj/project.pbxproj
  Myrror.xcworkspace/contents.xcworkspacedata
  Myrror/View/NewReflectionViewController.swift
  Myrror/View/ReflectionsViewController/ReflectionsView.swift
Labels: bug

#10 Feature/teste unitario u itest
  Myrror.xcodeproj/project.pbxproj
  Myrror/View/EmojiViewController.swift
  Myrror/View/ReflectionsViewController/ViewController.swift
  MyrrorTests/UnitTestCalendarHelper.swift
  MyrrorTests/UnitTestEmojiViewController.swift
  MyrrorTests/UnitTestViewController.swift
  MyrrorUITests/UITestChooseTopicViewController.swift
  MyrrorUITests/UITestNewReflectionViewController.swift
  MyrrorUITests/UITestViewController.swift
Labels: feature

#11 Feature/creating reflection
  Myrror.xcodeproj/project.pbxproj
  Myrror/ReflectionViewModel.swift
  Myrror/View/NewReflectionViewController.swift
  Myrror/View/ReflectionsViewController/ViewController.swift
  MyrrorTests/UnitTestNewReflectionViewController.swift
Labels: feature

#15 :sparkles: navegação ao finalizar reflection para pagina de reflections
  Myrror/View/NewReflectionViewController.swift
  Myrror/View/ReflectionsViewController/ViewController.swift
Labels: bug

#16 :sparkles: reflections deletaveis 😁
  Myrror/ReflectionViewModel.swift
  Myrror/View/ReflectionsViewController/ViewController.swift
Labels: feature

#17 :sparkles: feat: botão de tema livre na pagina de escolher topico
  Myrror.xcodeproj/project.pbxproj
  Myrror/Assets.xcassets/Images/writing.imageset/Contents.json
  Myrror/Assets.xcassets/Images/writing.imageset/writing.svg
  Myrror/View/ChooseTopicViewController/ChooseTopicView.swift
  Myrror/View/ChooseTopicViewController/ChooseTopicViewController.swift
Labels: feature

#18 Feature/keyboard bug
  Myrror/View/NewReflectionViewController.swift
Labels: feature

#19 💅 logo do app
  Myrror/Assets.xcassets/AppIcon.appiconset/100.png
  Myrror/Assets.xcassets/AppIcon.appiconset/1024.png
  Myrror/Assets.xcassets/AppIcon.appiconset/114.png
  Myrror/Assets.xcassets/AppIcon.appiconset/120.png
  Myrror/Assets.xcassets/AppIcon.appiconset/128.png
  Myrror/Assets.xcassets/AppIcon.appiconset/144.png
  Myrror/Assets.xcassets/AppIcon.appiconset/152.png
  Myrror/Assets.xcassets/AppIcon.appiconset/16.png
  Myrror/Assets.xcassets/AppIcon.appiconset/167.png
  Myrror/Assets.xcassets/AppIcon.appiconset/180.png
  Myrror/Assets.xcassets/AppIcon.appiconset/20.png
  Myrror/Assets.xcassets/AppIcon.appiconset/256.png
  Myrror/Assets.xcassets/AppIcon.appiconset/29.png
  Myrror/Assets.xcassets/AppIcon.appiconset/32.png
  Myrror/Assets.xcassets/AppIcon.appiconset/40.png
  Myrror/Assets.xcassets/AppIcon.appiconset/50.png
  Myrror/Assets.xcassets/AppIcon.appiconset/512.png
  Myrror/Assets.xcassets/AppIcon.appiconset/57.png
  Myrror/Assets.xcassets/AppIcon.appiconset/58.png
  Myrror/Assets.xcassets/AppIcon.appiconset/60.png
  Myrror/Assets.xcassets/AppIcon.appiconset/64.png
  Myrror/Assets.xcassets/AppIcon.appiconset/72.png
  Myrror/Assets.xcassets/AppIcon.appiconset/76.png
  Myrror/Assets.xcassets/AppIcon.appiconset/80.png
  Myrror/Assets.xcassets/AppIcon.appiconset/87.png
  Myrror/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: feature

#21 Feature/empty image bug
  Myrror.xcodeproj/project.pbxproj
  Myrror/View/ReflectionsViewController/ViewController.swift
Labels: bug

#36 :bug: bugfix: seleção de célula da tableview de reflections desabilitada
  Myrror/View/ReflectionsViewController/ViewController.swift
Labels: bug

#37 Bugfix/placeholder bug
  Myrror.xcodeproj/project.pbxproj
  Myrror/View/NewReflectionViewController.swift
Labels: bug

#41 :bricks: suporte a iOS 15
  Myrror.xcodeproj/project.pbxproj
Labels: feature

#43 Enhancement/calendar button area
  Myrror/View/ReflectionsViewController/ReflectionsView.swift
  Myrror/View/ReflectionsViewController/ViewController.swift
Labels: enhancement

#44 :sparkles: feat: alteração no estilo do dia atual e dia selecionado
  Myrror.xcodeproj/project.pbxproj
  Myrror/View/ReflectionsViewController/CalendarCollectionViewCell.swift
Labels: enhancement

#45 Enhancement/floating button
  Myrror.xcodeproj/project.pbxproj
  Myrror/View/ReflectionsViewController/ReflectionsView.swift
  Myrror/View/ReflectionsViewController/ViewController.swift
Labels: enhancement

#47 Feature/export reflection
  Myrror/View/ReflectionsViewController/ViewController.swift
Labels: feature

#48 :sparkles: feat: titulo da reflection de tema livre editável
  Myrror.xcodeproj/project.pbxproj
  Myrror/View/ChooseTopicViewController/ChooseTopicViewController.swift
  Myrror/View/NewReflectionViewController.swift
Labels: feature

#52 Feature/edit mode
  Myrror.xcodeproj/project.pbxproj
  Myrror/ReflectionViewModel.swift
  Myrror/View/ChooseTopicViewController/ChooseTopicViewController.swift
  Myrror/View/NewReflectionViewController.swift
  Myrror/View/ReflectionsViewController/ActionSheet.swift
  Myrror/View/ReflectionsViewController/ReflectionTableViewCell.swift
  Myrror/View/ReflectionsViewController/ReflectionsView.swift
  Myrror/View/ReflectionsViewController/ViewController.swift
Labels: feature

#51 💅 alteração no icone de o que aprendi de um livro para um cerebro
  Myrror/Assets.xcassets/Images/brain.imageset/Contents.json
  Myrror/Assets.xcassets/Images/brain.imageset/brain-svgrepo-com.svg
  Myrror/View/ChooseTopicViewController/ChooseTopicView.swift
Labels: enhancement

#53 :bug: bugfix: não estava mais sendo possivel inserir um titulo para a…
  Myrror/View/NewReflectionViewController.swift
Labels: bug

#61 💄 botão de compartilhar movido para a direita do botão de calendario
  Myrror/View/ReflectionsViewController/ReflectionsView.swift
  Myrror/View/ReflectionsViewController/ViewController.swift
Labels: enhancement

#63 Feature/empty screen image
  Myrror.xcodeproj/project.pbxproj
  Myrror/Assets.xcassets/AccentColor.colorset/Contents.json
  Myrror/Assets/nothing.json
  Myrror/View/ReflectionsViewController/ReflectionsView.swift
  lottie_simple_license.txt
Labels: enhancement

#68 💄 feat: Implementada a microinteração do botão de salvar reflection
  Myrror.xcodeproj/project.pbxproj
  Myrror/Assets/sucess.json
  Myrror/View/SetReflectionViewController/NewReflectionViewController.swift
  Myrror/View/SetReflectionViewController/SaveButtonView.swift
Labels: feature

#66 🧪 filanização dos testes
  Myrror/MyrrorUITests/UITestChooseTopicViewController.swift
  Myrror/MyrrorUITests/UITestNewReflectionViewController.swift
  Myrror/MyrrorUITests/UITestViewController.swift
  Myrror/ReflectionViewModel.swift
  MyrrorTests/UnitTestNewReflectionViewController.swift
  MyrrorTests/UnitTestreflectionViewModel.swift
Labels: test
